version: '3'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - ./redis:/data
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    volumes:
      - ./postgres:/var/lib/postgresql/data
  superset:
    build: .
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
